export type Lang = "zh" | "en";

export const dict = {
  zh: {
    brand: "O'rian Dessert",
    tagline: "高级手作草莓大福 · 会员系统",
    since: "SINCE 2023",
    nav_join: "成为会员",
    nav_admin: "员工后台",
    // landing
    hero_title: "O'rian 会员",
    hero_sub: "每一盒大福，都值得被记住。",
    hero_cta: "立即注册会员",
    hero_login: "我已是会员",
    feat_collect: "集点", feat_collect_d: "每盒 4 粒大福 = 1 枚印章",
    feat_reward: "奖励", feat_reward_d: "集满即可解锁专属甜点礼遇",
    feat_birthday: "生日礼", feat_birthday_d: "生日当天免费 2 粒大福",
    market_latest: "最近市集",
    // register
    reg_title: "注册会员",
    reg_sub: "只需一步，加入 O'rian 会员",
    reg_phone: "电话号码", reg_phone_ph: "例：0123456789",
    reg_ig: "Instagram 名字", reg_ig_ph: "例：abc123（不含 @）",
    reg_avatar: "头像（可选）",
    reg_birthday: "生日（可选）",
    reg_submit: "注册",
    reg_have: "已经是会员？用电话查询",
    reg_lookup: "查询我的会员卡",
    reg_lookup_ph: "输入注册时的电话号码",
    // member card
    mc_member: "会员",
    mc_phone: "电话",
    mc_birthday: "生日",
    mc_stamps: "当前印章",
    mc_redeemable: "可兑换奖励",
    mc_to_next: "距离下一个奖励",
    mc_grids: "格",
    mc_history_stamp: "集点记录",
    mc_history_reward: "兑换记录",
    mc_birthday_gift: "生日礼物",
    mc_birthday_ready: "今天是你的生日！出示此页领取免费 2 粒大福 🎂",
    mc_birthday_claimed: "今年的生日礼物已领取",
    mc_surprise: "惊喜奖励",
    mc_follow: "关注 Instagram",
    mc_following: "已关注 ♡",
    mc_qr_hint: "出示此 QR 给店员",
    mc_no_reward: "继续集点解锁奖励",
    mc_view_only: "本页面仅供查看，加点与兑换由店员操作",
    mc_locked: "未解锁",
    mc_unlocked: "可兑换",
    mc_claimed: "已兑换",
    // rewards
    r_unlock_at: "集满 {n} 格解锁",
    // admin
    a_login: "员工登录",
    a_username: "用户名",
    a_password: "密码",
    a_signin: "登录",
    a_dashboard: "后台总览",
    a_market_mode: "市集模式",
    a_customers: "会员列表",
    a_staff: "员工管理",
    a_settings: "系统设置",
    a_logout: "退出登录",
    a_today_new: "今日新增会员",
    a_today_stamps: "今日新增印章",
    a_today_redeem: "今日兑换",
    a_total_members: "总会员人数",
    a_month_new: "本月新增会员",
    a_month_redeem: "本月兑换数",
    a_recent: "最近顾客",
    a_active: "最活跃顾客",
    a_popular: "热门奖励",
    // market mode
    m_search: "搜索会员（电话 / IG）",
    m_scan: "扫描 QR",
    m_recent: "最近顾客",
    m_addstamp: "+1 印章",
    m_redeem: "兑换",
    m_done: "完成",
    m_no_result: "未找到会员",
    m_new_member: "＋ 新增会员",
    m_stamps_now: "当前印章",
    // customer detail
    c_detail: "会员详情",
    c_addstamp: "加印章 +1",
    c_substamp: "扣印章 -1",
    c_redeem_avail: "可兑换奖励",
    c_send_surprise: "发送惊喜奖励",
    c_edit: "修改资料",
    c_notes: "备注（可选）",
    c_surprise_ph: "输入惊喜奖励内容",
    c_send: "发送",
    c_open_ig: "打开 Instagram",
    // staff mgmt
    s_add: "新增员工",
    s_role_owner: "店主",
    s_role_staff: "员工",
    s_delete: "删除",
    // settings
    set_rewards: "奖励规则",
    set_market: "最近市集地点",
    set_place: "地点", set_date: "日期", set_time: "时间", set_note: "备注",
    set_export: "导出会员资料",
    set_export_csv: "导出 CSV",
    set_export_xlsx: "导出 Excel",
    set_save: "保存",
    set_saved: "已保存",
    // generic
    cancel: "取消", confirm: "确认", save: "保存", close: "关闭",
    loading: "加载中…", success: "成功", back: "返回",
    // errors
    err_phone_required: "请输入电话号码",
    err_phone_exists: "此电话号码已注册",
    err_phone_invalid: "电话号码格式不正确",
    err_not_found: "找不到此会员",
    err_login_failed: "用户名或密码错误",
    err_no_permission: "没有权限执行此操作",
    err_generic: "出错了，请重试",
    err_already_claimed: "本轮已兑换此奖励",
    err_not_enough: "印章不足，无法兑换",
    // footer
    f_privacy: "隐私政策", f_terms: "条款与细则",
  },
  en: {
    brand: "O'rian Dessert",
    tagline: "Premium Handmade Strawberry Daifuku · Membership",
    since: "SINCE 2023",
    nav_join: "Join",
    nav_admin: "Staff",
    hero_title: "O'rian Members",
    hero_sub: "Every box of daifuku deserves to be remembered.",
    hero_cta: "Become a Member",
    hero_login: "I'm already a member",
    feat_collect: "Collect", feat_collect_d: "1 box of 4 daifuku = 1 stamp",
    feat_reward: "Rewards", feat_reward_d: "Unlock exclusive dessert perks",
    feat_birthday: "Birthday", feat_birthday_d: "Free 2pcs on your birthday",
    market_latest: "Latest Market",
    reg_title: "Register",
    reg_sub: "One step to join O'rian membership",
    reg_phone: "Phone Number", reg_phone_ph: "e.g. 0123456789",
    reg_ig: "Instagram Handle", reg_ig_ph: "e.g. abc123 (no @)",
    reg_avatar: "Avatar (optional)",
    reg_birthday: "Birthday (optional)",
    reg_submit: "Register",
    reg_have: "Already a member? Look up by phone",
    reg_lookup: "Find my card",
    reg_lookup_ph: "Enter your registered phone",
    mc_member: "Member",
    mc_phone: "Phone",
    mc_birthday: "Birthday",
    mc_stamps: "Stamps",
    mc_redeemable: "Redeemable Rewards",
    mc_to_next: "To next reward",
    mc_grids: "",
    mc_history_stamp: "Stamp History",
    mc_history_reward: "Redemption History",
    mc_birthday_gift: "Birthday Gift",
    mc_birthday_ready: "It's your birthday! Show this page for a free 2pcs daifuku 🎂",
    mc_birthday_claimed: "This year's birthday gift has been claimed",
    mc_surprise: "Surprise Reward",
    mc_follow: "Follow on Instagram",
    mc_following: "Following ♡",
    mc_qr_hint: "Show this QR to staff",
    mc_no_reward: "Keep collecting to unlock rewards",
    mc_view_only: "View only — stamps & redemptions are handled by staff",
    mc_locked: "Locked",
    mc_unlocked: "Ready",
    mc_claimed: "Claimed",
    r_unlock_at: "Unlock at {n} stamps",
    a_login: "Staff Login",
    a_username: "Username",
    a_password: "Password",
    a_signin: "Sign In",
    a_dashboard: "Dashboard",
    a_market_mode: "Market Mode",
    a_customers: "Members",
    a_staff: "Staff",
    a_settings: "Settings",
    a_logout: "Log Out",
    a_today_new: "New Members Today",
    a_today_stamps: "Stamps Today",
    a_today_redeem: "Redemptions Today",
    a_total_members: "Total Members",
    a_month_new: "New This Month",
    a_month_redeem: "Redemptions This Month",
    a_recent: "Recent Customers",
    a_active: "Most Active",
    a_popular: "Popular Rewards",
    m_search: "Search (phone / IG)",
    m_scan: "Scan QR",
    m_recent: "Recent",
    m_addstamp: "+1 Stamp",
    m_redeem: "Redeem",
    m_done: "Done",
    m_no_result: "No member found",
    m_new_member: "＋ New Member",
    m_stamps_now: "Stamps",
    c_detail: "Member Detail",
    c_addstamp: "Add Stamp +1",
    c_substamp: "Remove Stamp -1",
    c_redeem_avail: "Available Rewards",
    c_send_surprise: "Send Surprise Reward",
    c_edit: "Edit Profile",
    c_notes: "Notes (optional)",
    c_surprise_ph: "Enter surprise reward content",
    c_send: "Send",
    c_open_ig: "Open Instagram",
    s_add: "Add Staff",
    s_role_owner: "Owner",
    s_role_staff: "Staff",
    s_delete: "Delete",
    set_rewards: "Reward Rules",
    set_market: "Latest Market Location",
    set_place: "Place", set_date: "Date", set_time: "Time", set_note: "Note",
    set_export: "Export Members",
    set_export_csv: "Export CSV",
    set_export_xlsx: "Export Excel",
    set_save: "Save",
    set_saved: "Saved",
    cancel: "Cancel", confirm: "Confirm", save: "Save", close: "Close",
    loading: "Loading…", success: "Success", back: "Back",
    err_phone_required: "Please enter a phone number",
    err_phone_exists: "This phone number is already registered",
    err_phone_invalid: "Invalid phone number format",
    err_not_found: "Member not found",
    err_login_failed: "Wrong username or password",
    err_no_permission: "You don't have permission for this",
    err_generic: "Something went wrong, please try again",
    err_already_claimed: "This reward was already claimed this cycle",
    err_not_enough: "Not enough stamps to redeem",
    f_privacy: "Privacy Policy", f_terms: "Terms & Conditions",
  },
} as const;

// Keys come from the zh dictionary; values are plain strings so that the
// en dictionary (with different literal values) is structurally assignable.
export type Dict = Record<keyof typeof dict.zh, string>;
export function t(lang: Lang): Dict {
  return dict[lang];
}
